[package]
name = "cjseq"
version = "0.2.0"
description = "Conversion CityJSON <=> CityJSONSeq"
authors = ["Hugo Ledoux <h.ledoux@tudelft.nl>"]
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/cityjson/cjseq"
repository = "https://github.com/cityjson/cjseq"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# serde_derive = "1.0"


